Repository wecode-bootcamp-korea/41-2nd-ShallWe-frontend, pull requests merged in 2023-02, with the labels that each got.

#29 [41기 장찬영] 메인 카테고리바 구현
  src/pages/Main/Component/CategoryBar.js
  src/pages/Main/Component/images/animation.png
  src/pages/Main/Component/images/documentary.png
  src/pages/Main/Component/images/test.png
  src/pages/Main/Component/images/theater.png
  src/pages/Main/Main.js
Labels: 완료

#28 [41기 장찬영] 카테고리 기능구현
  public/data/category.json
  src/components/ProductCards.js
  src/config.js
  src/pages/Category/Category.js
  src/pages/Category/CategoryModal.js
  src/pages/Category/ProductCard.js
  src/pages/Category/images/check.png
Labels: 완료

#30 [41기 김성재] Modify: router수정 및 Nav 경로수정
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/MyPage/components/MyShallwe.js
  src/pages/MyPage/components/Review.js
  src/pages/MyPage/components/UserInfo.js
  src/pages/MyPage/images/ticket.png
Labels: 수정 요청

#15 [41기 박채연] Detail 페이지 레이아웃 구현
  package-lock.json
  package.json
  public/data/list.json
  src/Router.js
  src/index.js
  src/pages/MovieDetail/Detail.js
  src/pages/MovieDetail/DetailOption.js
  src/pages/MovieDetail/InfoSide.js
  src/pages/MovieDetail/cinema.png
  src/pages/MovieDetail/share.png
  src/styles/mixin.js
Labels: 완료

#31 [41기 장찬영] mini slider 패치경로 수정
  src/pages/Main/Component/MiniSlider.js
Labels: 완료

#32 [41기 김성재] Add: Subscription 페이지 수정
  src/pages/MyPage/components/Review.js
  src/pages/Subscription/Subscription.js
  src/pages/Subscription/components/SubCard.js
Labels: 완료

#34 [41기 박채연] Detail 페이지 재구현
  package-lock.json
  package.json
  public/images/location.png
  public/index.html
  src/Router.js
  src/pages/MovieDetail/Detail.js
  src/pages/MovieDetail/DetailOption.js
  src/pages/MovieDetail/InfoSide.js
  src/pages/MovieDetail/KakaoMap.js
Labels: 완료

#36 [41기 김성재] FIX: router 수정
  src/Router.js
Labels: 완료

#35 [41기 박예솔] Add movieCart & kakaoPay
  public/favicon.ico
  public/images/logo.png
  src/assets/images/payment.png
  src/components/KakaoPay/KakaoPay.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/MovieCart/MovieCart.js
  src/pages/MovieCart/MovieItem.js
  src/pages/MovieCart/MovieReceipt.js
  src/pages/MovieCart/PayFail.js
  src/pages/MovieCart/PaySuccess.js
Labels: 완료

#38 [41기 장찬영] router 수정
  src/Router.js
Labels: 완료

#39 [41기 박채연] Intro페이지 구현
  public/images/bg.jpg
  public/images/intro1.avif
  public/images/intro2.avif
  public/images/intro3.jpeg
  public/images/intro4.jpeg
  public/images/intro5.avif
  public/images/intro6.jpeg
  public/images/intro7.avif
  src/Router.js
  src/components/Button.js
  src/pages/Main/Intro.js
  src/pages/Main/IntroStyle.js
Labels: 완료

#41 [41기 장찬영] nav 잔여좌석 수정
  src/components/Nav/Nav.js
  src/pages/Main/Component/LimitBox.js
Labels: 리뷰 진행 중

#42 [41기 장찬영] Modify: 버튼 수정
  src/components/Button.js
Labels: 완료

#37 [41기 김성재] Feature/mypage refunds+sub func
  src/Router.js
  src/config.js
  src/pages/MyPage/components/Call.js
  src/pages/MyPage/components/Cart.js
  src/pages/MyPage/components/Refunds.js
  src/pages/MyPage/components/Review.js
  src/pages/MyPage/components/Review/ReviewComment.js
  src/pages/MyPage/components/Review/ReviewEdit.js
  src/pages/MyPage/components/Subscribe.js
  src/pages/MyPage/images/subscribe.jpeg
  src/pages/Subscription/Subscription.js
  src/pages/Subscription/components/SubCard.js
Labels: 완료
